### ISSUE TITLE
Design the account page in Figma

### ISSUE THREAD

**Issue by RobertMartinis** [JakobPaulsson/EasyEats#3]
There's currently no prototype for how the account page should look like in [Figma](https://www.figma.com/file/O1El98A6ZywAQcCTRwA5fz/Easy-Eats?type=design&node-id=0%3A1&mode=design&t=8Ax9o20nOa8jQaQ2-1).

**Comment by JakobPaulsson** [comment]
No cap fr fr

**Comment by JakobPaulsson** [comment]
yup
